name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/.go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('./srv/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod tidy
      working-directory: ./srv

    - name: Run linter
      run: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint && golangci-lint run
      working-directory: ./srv

    - name: Build
      run: go build -v ./...
      working-directory: ./srv

    - name: Test
      run: go test -v ./...
      working-directory: ./srv
      
    - name: Upload Coverage Report
      run: |
        go test -coverprofile=coverage.out ./...
        go tool cover -html=coverage.out -o coverage.html
      working-directory: ./srv 
